
import type {Metadata} from 'next';
import './globals.css';
import {ReactNode} from 'react';

export const metadata: Metadata = {
  title: 'Excildraw clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{children: ReactNode}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
